postgres:
  image: postgres
  environment:
    - POSTGRES_DB=taiga
    - POSTGRES_USER=taiga
    - POSTGRES_PASSWORD=password
taiga:
  build: .
  ports:
    - 80:80
    # - 443:443 # To enable SSL, uncomment this line
  links:
    - postgres
  environment:
    - TAIGA_HOSTNAME=localhost

    # TAIGA_SLEEP haults Taiga from starting for 30 seconds,
    # this gives the database container time to initialize.
    # If you're using an external database you can remove this.
    - TAIGA_SLEEP=30

    # TAIGA_SSL: "True" # To enable SSL, uncomment this line

    # To use an external database, fill in these values and remove
    # the link to the postgres service.
    - TAIGA_DB_NAME=taiga
    - TAIGA_DB_HOST=postgres
    - TAIGA_DB_USER=taiga
    - TAIGA_DB_PASSWORD=password

    # To enable email sending fill these values
    - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
    - EMAIL_USE_TLS=True
    - EMAIL_HOST=smtp.example.com
    - EMAIL_PORT=587
    - EMAIL_HOST_USER=user@example.com
    - EMAIL_HOST_PASSWORD=password

    - DEFAULT_FROM_EMAIL=user@example.com
